### ISSUE TITLE
using deprecated pandas.np module

### ISSUE THREAD

**Issue by katarinagresova** [robertopreste/apybiomart#62]
* apybiomart version: 0.5.2
* Python version: 3.6.9
* Operating System: Google Colab

### Description

Pandas deprecated pandas.np (discussed in this [issue](https://github.com/pandas-dev/pandas/issues/30296)) and will remove it in future versions. apybiomart code should adapt to it.

### Warning

```
/usr/local/lib/python3.6/dist-packages/apybiomart/classes.py:210: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead
  df.replace(pd.np.nan, "", inplace=True)
```

**Comment by robertopreste** [comment]
Thanks @katarinagresova for filing this issue.
This should be fixed now in version 0.5.3.
